### ISSUE TITLE
닉네임 설정 시 띄어쓰기 버그

### ISSUE THREAD

**Issue by alstj0127** [dongcheolpark/Yacht_Dice_C#29]
**Describe the bug**
닉네임을 설정할 때 띄어쓰기를 사용하면 프로그램이 먹통이 되는 현상이 있습니다.

**Expected behavior**
스페이스가 버퍼에 계속 남아서 발생하는 것으로 추정

**Additional context**
해결해죠

**Comment by dongcheolpark** [comment]
해결
