### ISSUE TITLE
주사위와 점수판 선택 기능 추가

### ISSUE THREAD

**Issue by alstj0127** [dongcheolpark/Yacht_Dice_C#44]
주사위를 선택하는 조작키와 홀드하는 키, 점수판 선택 기능을 추가해야 합니다.

**Comment by dongcheolpark** [comment]
조작키는 방향키, 홀드는 z, 점수판선택은 x키

**Comment by dongcheolpark** [comment]
방향키 조작시 그래픽 처리 관련 브랜치 만들겠습니다
control_graphic

**Comment by dongcheolpark** [comment]
점수판 선택기능은 여기서 하지말고 새롭게 이슈를 만들죠

**Comment by dongcheolpark** [comment]
추가했습니다 #89

**Comment by dongcheolpark** [comment]
주사위 조작 완료
